In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print (torch.__version__)

1.10.2+cu102


## Introduction to Tensors
### Creating tensors

In [8]:
# scalar 
scalar = torch.tensor(7)
scalar


tensor(7)

In [9]:
scalar.ndim

0

In [10]:
scalar.item()

7

In [11]:
# vector 
vector = torch.tensor([7,7])
vector

tensor([7, 7])

In [12]:
vector.ndim

1

In [14]:
vector.shape

torch.Size([2])

In [15]:
# MATRIX
matrix= torch.tensor([[7,8],
                     [9,10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [16]:
matrix.ndim

2

In [17]:
matrix[0]

tensor([7, 8])

In [18]:
matrix[1]

tensor([ 9, 10])

In [19]:
matrix.shape

torch.Size([2, 2])

In [23]:
# Tensor

Tensor = torch.tensor([[[1,2,3],
                        [3,6,9],
                       [2,5,4]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [24]:
Tensor.ndim

3

In [25]:
Tensor.shape

torch.Size([1, 3, 3])

In [26]:
Tensor[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

### Random tensors 

In [32]:
# create a random tensors

random_tensor = torch.rand(3,4)
random_tensor

tensor([[0.1365, 0.2402, 0.2135, 0.5728],
        [0.3929, 0.4145, 0.1712, 0.9882],
        [0.7466, 0.8632, 0.1133, 0.6109]])

In [36]:
# create a random tensor with similar shape to an image tensor 
random_image_size_tensor = torch.rand(size=(224,224,3)) # height ,width ,colour chanel
random_image_size_tensor.shape ,random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [39]:
# create a tensor of all zeros

zeros= torch.zeros(size=(3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [40]:
# create  a tensor of all ones 

ones= torch.ones(size=(3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [41]:
ones.dtype

torch.float32

### Cearting a range of tensors and tensors-like


In [47]:
# tensor range 
one_to_ten=torch.arange(start=1,end=11,step=1)
one_to_ten
    

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
# tensor like 
ten_zeros=torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [2]:
### Tensor datatype
float_32_tensor = torch.tensor([3.0,6.0,9.0],dtype = None,device="cuda",requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [55]:
float_32_tensor.dtype

torch.float32

In [3]:
float_16_tensor =float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [4]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.], device='cuda:0')

In [7]:
int_32_tensor = torch.tensor([3,6,9],dtype=torch.int64)
int_32_tensor

tensor([3, 6, 9])

In [8]:
float_32_tensor*int_32_tensor

RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu!

### Geting information from tensor 

In [10]:
some_tensor = torch .rand(3,4)
some_tensor

tensor([[0.1157, 0.0252, 0.5691, 0.5949],
        [0.8792, 0.6388, 0.7016, 0.9762],
        [0.2457, 0.3483, 0.5922, 0.0713]])

In [12]:
some_tensor.size,some_tensor.shape

(<function Tensor.size>, torch.Size([3, 4]))

In [15]:
print(some_tensor)
print(f"Datatype of Tensor:{some_tensor.dtype}")
print(f"Shape of tensor:{some_tensor.size}")
print(f"Devisce tensor is on:{some_tensor.device}")

tensor([[0.1157, 0.0252, 0.5691, 0.5949],
        [0.8792, 0.6388, 0.7016, 0.9762],
        [0.2457, 0.3483, 0.5922, 0.0713]])
Datatype of Tensor:torch.float32
Shape of tensor:<built-in method size of Tensor object at 0x7f5b58b072c0>
Devisce tensor is on:cpu


### Manipulating Tensor (tensor operation)

#### Addition , subtraction , multiplication(element-wise), Division ,Matrix multiplication  

In [17]:
tensor= torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [18]:
tensor * 10 

tensor([10, 20, 30])

In [19]:
tensor - 10 

tensor([-9, -8, -7])

In [20]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [21]:
torch.add(tensor,10)

tensor([11, 12, 13])

### matrix multiplication  ( Dot product)

In [26]:
# element wise multiplication
print(tensor, "*" ,tensor)
print (f"Equals:{tensor* tensor}")

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals:tensor([1, 4, 9])


In [27]:
# matrix multiplication 
torch.matmul(tensor,tensor)

tensor(14)

### Tensor aggregation : min,max,sum,mean,etc

In [38]:
x= torch.arange(1,100,10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [30]:
torch.min(x)

tensor(0)

In [31]:
torch.max(x)

tensor(90)

In [33]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [34]:
torch.sum(x)

tensor(450)

## Finding the positional min and max

In [39]:
x.argmin()

tensor(0)

In [40]:
x.argmax()

tensor(9)

### Reshaping ,stacking (concatenate) , squeezing and unsqueezing 

In [41]:
x= torch.arange(1.,10.)
x,x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [46]:
# Reshape - add an extera dimension

x_reshaped  = x. reshape(9,1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [47]:
# chnage the viwe 
z = x.view(1,9)
z,z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [48]:
z[:,0]=5
z,x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [50]:
# stack tensor on top of each other 
x_stacked = torch.stack([x,x,x,x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [51]:
# squzzing -  removes all singel dimension from a trget tenor 
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [52]:
x_reshaped.shape

torch.Size([9, 1])

In [53]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [54]:
x_reshaped.squeeze().shape

torch.Size([9])

### Indexing (select data from tensor )

In [55]:
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [56]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [57]:
x[0][0]

tensor([1, 2, 3])

In [58]:
x[0][0][0]

tensor(1)